version: '3.3'
services:
  pg:
    image: postgres
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data 
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=saga1234

  queue:
    image: rabbitmq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=saga
      - RABBITMQ_DEFAULT_PASS=saga
      
